### PR TITLE
Clarify Readme and fix SerialisableCertificate

### PR DESCRIPTION
**Pull request by caemor**
Tried to fix and clarify my additionally added issues from #95.
- Removed SerialisableCertificate from Public Interface and adapted  other stuff around this change
- Clarified Readme that currently only 3rd option is implemented, but others will follow

### CODE REVIEW

**Comment by caemor** [comment]
It's a clippy failure on mutable_key_types elsewhere.

```
❯ cargo clippy --workspace --all-targets
    Checking mock-quic-p2p v0.1.0 (/home/caemor/github/quic-p2p/mock)
error: mutable key type
   --> mock/src/tests.rs:354:5
    |
354 |     let received_messages = b.received_messages(&a.addr());
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[deny(clippy::mutable_key_type)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mutable_key_type

error: mutable key type
   --> mock/src/tests.rs:600:59
    |
600 |     fn received_messages(&self, src_addr: &SocketAddr) -> FxHashSet<Bytes> {
    |                                                           ^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mutable_key_type

error: mutable key type
   --> mock/src/tests.rs:601:9
    |
601 |         let mut received_messages = FxHashSet::default();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mutable_key_type

error: mutable key type
   --> mock/src/tests.rs:610:59
    |
610 | fn expected_messages_received(sent: Vec<Bytes>, received: FxHashSet<Bytes>) {
    |                                                           ^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mutable_key_type

error: mutable key type
   --> mock/src/tests.rs:611:5
    |
611 |     let expected: FxHashSet<_> = sent.into_iter().collect();
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mutable_key_type

error: aborting due to 5 previous errors

error: could not compile `mock-quic-p2p`.

To learn more, run the command again with --verbose.
```

**Comment by dirvine** [comment]
Can you please look at conflicts (only readme so easy enough I hope)

**Comment by caemor** [comment]
Sorry for the late response. Conflict should be fixed

**Review by lionel-faber — APPROVED** [review]
Apologies for the delay @caemor 
Thanks for this.

**Pull request merged**
