### PR TITLE
Improve README text

### PR DESCRIPTION
**Pull request by berkus**
* Fix small typos
* Make sentences more clear

### CODE REVIEW

**Comment by berkus** [comment]
Not very active community, I see...

**Comment by willief** [comment]
@berkus     I suspect our devs have better things to do than piss about with small typos. They are doing _real_ work while all you can do is whine and stamp your feet cos your "look at me" little issue has been correctly triaged.

**Review by dirvine — APPROVED** [review]
Thank you for this. We will merge straight away. Nice work.

**Comment by berkus** [comment]
@willief I see, also very toxic community, thanks for the warning.

**Comment by frabrunelle** [comment]
@berkus I just contacted @willief and agreed to delete his comment. I think we should all make an extra effort to be welcoming of developer contributions. Thanks for your contribution and sorry for not noticing it earlier. Cheers!

**Pull request merged**
